### PR TITLE
Feature/milestone 1

### PR DESCRIPTION
**Pull request by ixboy**
Hello, this is my first code review request from the Social media website project, I have prepared the project's data architecture documentation and completed all the requirements for milestone 1.
please do review my work and inform me if I can proceed to the next milestone.
Thanks in advance.

Best regards.
Ismael :)

### CODE REVIEW

**Review by rindrajosia — CHANGES_REQUESTED** [review]
Invalid :cry: 
**Linters config**: Do not make any changes in config files - they represent style guidelines that you share with your team - which is a group of all Microverse students. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/linter_config.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/) )
Please, use files in this [repo](https://github.com/microverseinc/linters-config/tree/master/ror)

**Comment by ixboy** [comment]
> Invalid cry
> **Linters config**: Do not make any changes in config files - they represent style guidelines that you share with your team - which is a group of all Microverse students. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/linter_config.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/) )
> Please, use files in this [repo](https://github.com/microverseinc/linters-config/tree/master/ror)

Hello and Thank You for your review.
I haven't changed anything, in fact I did not even touch the linter config files. I believed it came with the repo that I forked.

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
# **Changes Requested 🛑♻**

<hr>

Hello there :)
Great job working on this milestone. You've done it right with the ERD, the tables' columns are all correctly set up including the PKs and the FKs except for just one FK. Please see my comment below:-

- [x] In the Post table, the user_id column should be the FK of the table, not the content. Kindly adjust that.

<hr>

That's it! Please do the changes above and you'll be good to go to the next milestone 💯 
Good luck and happy coding with the next. 😊👨‍💻💻

<hr>

## **Note [OPTIONAL]**
It'd be nice if you modify the following point in your ERD. (professionally)
- Just to make sure you understand what's a PK means. Every table created within a database has a primary key which is the ID of that table, this means, for example, The User table has a primary key called ID, every time a user is created, it gets an id unique number that belongs to it. The point is that it's not necessary to make the PKs' names like "user_id". It's just ID :)

**Review by umairarshadbutt — APPROVED** [review]
# **Status: PROJECT APPROVED** :champagne:
Excellent job on this project guys. :fireworks: Keep it up.
##
- All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.
- Congratulations on the splendid job @ixboy ! :+1: 
- You can now merge to master and submit the project completion form :rocket: . I wish you all the very best in your next tasks :1st_place_medal:
##
HAPPY CODING :computer:
**[Umair Arshad (Code Reviewer)](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Pull request merged**
